version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8088:8088
    networks:
      - hqs-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/hqs?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb

    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    restart: always
    command: --default-authentication-plugin=mysql_native_password --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    networks:
      - hqs-net
    environment:
      MYSQL_DATABASE: hqs
      MYSQL_USER: root
      MYSQL_PASSWORD: apache7
      MYSQL_ROOT_PASSWORD: apache7
    volumes:
      - ./database:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
networks:
  hqs-net: